return {
	-- 	"yetone/avante.nvim",
	-- 	-- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
	-- 	-- ⚠️ must add this setting! ! !
	-- 	build = vim.fn.has("win32") ~= 0 and "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false"
	-- 		or "make",
	-- 	event = "VeryLazy",
	-- 	version = false,
	-- 	---@module "avante"
	-- 	---@type avante.Config
	-- 	opts = {
	-- 		provider = "cursor",
	-- 		mode = "agentic",
	-- 		acp_providers = {
	-- 			cursor = {
	-- 				command = "/home/unbalanced/.local/bin/agent",
	-- 				args = { "acp" },
	-- 				auth_method = "cursor_login",
	-- 				env = {
	-- 					HOME = os.getenv("HOME"),
	-- 					PATH = os.getenv("PATH"),
	-- 				},
	-- 			},
	-- 		},
	-- 		behaviour = {
	-- 			auto_focus_sidebar = true,
	-- 			auto_approve_tool_permissions = false,
	-- 			auto_apply_diff_after_generation = false,
	-- 			support_paste_from_clipboard = true,
	-- 			auto_suggestions = true,
	-- 			auto_set_keymaps = true,
	-- 			auto_add_current_file = true,
	-- 			minimize_diff = true,
	-- 			auto_check_diagnostics = true,
	-- 			confirmation_ui_style = "inline_buttons",
	-- 			acp_follow_agent_locations = true,
	-- 			enable_fastapply = false,
	-- 		},
	-- 	},
	-- 	dependencies = {
	-- 		"nvim-lua/plenary.nvim",
	-- 		"MunifTanjim/nui.nvim",
	-- 		--- The below dependencies are optional,
	-- 		"nvim-telescope/telescope.nvim",
	-- 		"hrsh7th/nvim-cmp",
	-- 		"nvim-tree/nvim-web-devicons",
	-- 		"stevearc/dressing.nvim",
	-- 		{
	-- 			-- support for image pasting
	-- 			"HakonHarnes/img-clip.nvim",
	-- 			event = "VeryLazy",
	-- 			opts = {
	-- 				-- recommended settings
	-- 				default = {
	-- 					embed_image_as_base64 = false,
	-- 					prompt_for_file_name = false,
	-- 					drag_and_drop = {
	-- 						insert_mode = true,
	-- 					},
	-- 					-- required for Windows users
	-- 					use_absolute_path = true,
	-- 				},
	-- 			},
	-- 		},
	-- 		{
	-- 			-- Make sure to set this up properly if you have lazy=true
	-- 			"MeanderingProgrammer/render-markdown.nvim",
	-- 			opts = {
	-- 				file_types = { "markdown", "Avante" },
	-- 			},
	-- 			ft = { "markdown", "Avante" },
	-- 		},
	-- 	},
}
